### ISSUE TITLE
lint export collection

### ISSUE THREAD

**Issue by rusinikita** [rusinikita/devex#4]
## Goal

Visualizing problematic files with many codesmells and codechanges. It will help estimate and prioritize tech debt.

## Task

- [ ] Add function to parce lint result file and save issues to database. Function must be placed inside datasource/lint package.
- [ ] Add function to parse and save data to database. Function must be placed inside datacollector package.
- [ ] Add command "lint <project alias> <file name>" that uses function above.

## Data structure

File format: checkstyle as widely supported output format (golangci-lint, eslint). Example `golangci-lint run --out-format=checkstyle >> out.txt` [out.txt](https://github.com/rusinikita/devex/files/12312535/out.txt)
Draft: Issues(file_id, title, description, severenity)

## Test cases

- Same list of issues from lint export file placed into database table.
- Importing new linter results do not cause data dublication. Previous project issues removed.

P.S.

Inspired by [codescene](https://codescene.com/for-developers)
